//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP3_DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonementas
    {
        public Abonementas()
        {
            this.Uzsakymai = new HashSet<Uzsakymai>();
        }
    
        public int Id { get; set; }
        public string Pavadinimas { get; set; }
        public Nullable<float> Trukme { get; set; }
        public string Aprasymas { get; set; }
        public decimal Kaina { get; set; }
    
        public virtual ICollection<Uzsakymai> Uzsakymai { get; set; }
    }
}
