//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP3_DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamintojas
    {
        public Gamintojas()
        {
            this.Treniruoklis = new HashSet<Treniruoklis>();
        }
    
        public string Pavadinimas { get; set; }
        public string Adresas { get; set; }
        public string TelNr { get; set; }
    
        public virtual ICollection<Treniruoklis> Treniruoklis { get; set; }
    }
}
