//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;

namespace TOP3_DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klientas
    {
        public Klientas()
        {
            this.TreniruoklisIstorija = new HashSet<TreniruoklisIstorija>();
            this.Uzsakymai = new HashSet<Uzsakymai>();
        }
    
        public int Id { get; set; }
        public string Adresas { get; set; }
        public string GimimoData { get; set; }
        public string Vardas { get; set; }
        public Nullable<double> Svoris { get; set; }
        public Nullable<int> TrenerioId { get; set; }
    
        public virtual ICollection<TreniruoklisIstorija> TreniruoklisIstorija { get; set; }
        public virtual ICollection<Uzsakymai> Uzsakymai { get; set; }
        public virtual Treneris Treneris { get; set; }

        public string getInfo()
        {
            return ((new StringBuilder()).Append(this.Vardas).Append(" ").Append(this.GimimoData).Append(" ").Append(this.Adresas).ToString());

        }
    }
}
