//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP3_DB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDbEntities1 : DbContext
    {
        public TestDbEntities1()
            : base("name=TestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Abonementas> Abonementas { get; set; }
        public DbSet<Gamintojas> Gamintojas { get; set; }
        public DbSet<Klientas> Klientas { get; set; }
        public DbSet<Treneris> Treneris { get; set; }
        public DbSet<Treniruoklis> Treniruoklis { get; set; }
        public DbSet<TreniruoklisIstorija> TreniruoklisIstorija { get; set; }
        public DbSet<Uzsakymai> Uzsakymai { get; set; }
    }
}
