//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP3_DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreniruoklisIstorija
    {
        public int Id { get; set; }
        public int KlientoId { get; set; }
        public int TreniruoklioId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Klientas Klientas { get; set; }
        public virtual Treniruoklis Treniruoklis { get; set; }
    }
}
