//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP3_DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treniruoklis
    {
        public int Id { get; set; }
        public string Pavadinimas { get; set; }
        public Nullable<System.DateTime> EksplPradziosData { get; set; }
        public string RaumenuGrupe { get; set; }
        public string GamintojoPavadinimas { get; set; }
        public Nullable<System.DateTime> PagaminimoData { get; set; }
    
        public virtual Gamintojas Gamintojas { get; set; }
        public virtual TreniruoklisIstorija TreniruoklisIstorija { get; set; }
    }
}
